services:
  postgres_database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: cpereiramt
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
      POSTGRES_DB: bd_test
    ports:
       - "5332:5432"